INSERT INTO animal_crossing
(img, name, type )

VALUES
('Agrias butterfly.png','Agrias butterfly','Bugs'),
('Ant.png','Ant','Bugs'),
('Atlas moth.png','Atlas moth','Bugs'),
('Bagworm.png','Bagworm','Bugs'),
('Banded dragonfly.png','Banded dragonfly','Bugs'),
('Bell cricket.png','Bell cricket','Bugs'),
('Blue weevil beetle.png','Blue weevil beetle','Bugs'),
('Brown cicada.png','Brown cicada','Bugs'),
('Centipede.png','Centipede','Bugs'),
('Cicada shell.png','Cicada shell','Bugs'),
('Citrus long-horned beetle.png','Citrus long-horned beetle','Bugs'),
('Common bluebottle.png','Common bluebottle','Bugs'),
('Common butterfly.png','Common butterfly','Bugs'),
('Cricket.png','Cricket','Bugs'),
('Cyclommatus stag.png','Cyclommatus stag','Bugs'),
('Damselfly.png','Damselfly','Bugs'),
('Darner dragonfly.png','Darner dragonfly','Bugs'),
('Diving beetle.png','Diving beetle','Bugs'),
('Drone beetle.png','Drone beetle','Bugs'),
('Dung beetle.png','Dung beetle','Bugs'),
('Earth-boring dung beetle.png','Earth-boring dung beetle','Bugs'),
('Emperor butterfly.png','Emperor butterfly','Bugs'),
('Evening cicada.png','Evening cicada','Bugs'),
('Firefly.png','Firefly','Bugs'),
('Flea.png','Flea','Bugs'),
('Fly.png','Fly','Bugs'),
('Giant cicada.png','Giant cicada','Bugs'),
('Giant stag.png','Giant stag','Bugs'),
('Giant water bug.png','Giant water bug','Bugs'),
('Giraffe stag.png','Giraffe stag','Bugs'),
('Golden stag.png','Golden stag','Bugs'),
('Goliath beetle.png','Goliath beetle','Bugs'),
('Grasshopper.png','Grasshopper','Bugs'),
('Great purple emperor.png','Great purple emperor','Bugs'),
('Hermit crab.png','Hermit crab','Bugs'),
('Honeybee.png','Honeybee','Bugs'),
('Horned atlas.png','Horned atlas','Bugs'),
('Horned dynastid.png','Horned dynastid','Bugs'),
('Horned elephant.png','Horned elephant','Bugs'),
('Horned hercules.png','Horned hercules','Bugs'),
('Jewel beetle.png','Jewel beetle','Bugs'),
('Ladybug.png','Ladybug','Bugs'),
('Long locust.png','Long locust','Bugs'),
('Madagascan sunset moth.png','Madagascan sunset moth','Bugs'),
('Man-faced stink bug.png','Man-faced stink bug','Bugs'),
('Mantis.png','Mantis','Bugs'),
('Migratory locust.png','Migratory locust','Bugs'),
('Miyama stag.png','Miyama stag','Bugs'),
('Mole cricket.png','Mole cricket','Bugs'),
('Monarch butterfly.png','Monarch butterfly','Bugs'),
('Mosquito.png','Mosquito','Bugs'),
('Moth.png','Moth','Bugs'),
('Orchid mantis.png','Orchid mantis','Bugs'),
('Paper kite butterfly.png','Paper kite butterfly','Bugs'),
('Peacock butterfly.png','Peacock butterfly','Bugs'),
('Pill bug.png','Pill bug','Bugs'),
('Pondskater.png','Pondskater','Bugs'),
('Queen Alexandra''s birdwing.png','Queen Alexandra''s birdwing','Bugs'),
('Rainbow stag.png','Rainbow stag','Bugs'),
('Rajah Brooke''s birdwing.png','Rajah Brooke''s birdwing','Bugs'),
('Red dragonfly.png','Red dragonfly','Bugs'),
('Rice grasshopper.png','Rice grasshopper','Bugs'),
('Robust cicada.png','Robust cicada','Bugs'),
('Rosalia batesi beetle.png','Rosalia batesi beetle','Bugs'),
('Saw stag.png','Saw stag','Bugs'),
('Scarab beetle.png','Scarab beetle','Bugs'),
('Scorpion.png','Scorpion','Bugs'),
('Snail.png','Snail','Bugs'),
('Spider.png','Spider','Bugs'),
('Stinkbug.png','Stinkbug','Bugs'),
('Tarantula.png','Tarantula','Bugs'),
('Tiger beetle.png','Tiger beetle','Bugs'),
('Tiger butterfly.png','Tiger butterfly','Bugs'),
('Violin beetle.png','Violin beetle','Bugs'),
('Walker cicada.png','Walker cicada','Bugs'),
('Walking leaf.png','Walking leaf','Bugs'),
('Walking stick.png','Walking stick','Bugs'),
('Wasp.png','Wasp','Bugs'),
('Wharf roach.png','Wharf roach','Bugs'),
('Yellow butterfly.png','Yellow butterfly','Bugs'),
('Anchovy.png','Anchovy','Fish'),
('Angelfish.png','Angelfish','Fish'),
('Arapaima.png','Arapaima','Fish'),
('Arowana.png','Arowana','Fish'),
('Barred knifejaw.png','Barred knifejaw','Fish'),
('Barreleye.png','Barreleye','Fish'),
('Betta.png','Betta','Fish'),
('Bitterling.png','Bitterling','Fish'),
('Black bass.png','Black bass','Fish'),
('Blowfish.png','Blowfish','Fish'),
('Blue marlin.png','Blue marlin','Fish'),
('Bluegill.png','Bluegill','Fish'),
('Butterfly fish.png','Butterfly fish','Fish'),
('Carp.png','Carp','Fish'),
('Catfish.png','Catfish','Fish'),
('Char.png','Char','Fish'),
('Cherry salmon.png','Cherry salmon','Fish'),
('Clown fish.png','Clown fish','Fish'),
('Clownfish.png','Clownfish','Fish'),
('Coelacanth.png','Coelacanth','Fish'),
('Crawfish.png','Crawfish','Fish'),
('Crucian carp.png','Crucian carp','Fish'),
('Dab.png','Dab','Fish'),
('Dace.png','Dace','Fish'),
('Dorado.png','Dorado','Fish'),
('Football fish.png','Football fish','Fish'),
('Freshwater goby.png','Freshwater goby','Fish'),
('Frog (fish).png','Frog (fish)','Fish'),
('Frog.png','Frog','Fish'),
('Gar.png','Gar','Fish'),
('Giant snakehead.png','Giant snakehead','Fish'),
('Giant trevally.png','Giant trevally','Fish'),
('Golden trout.png','Golden trout','Fish'),
('Goldfish.png','Goldfish','Fish'),
('Great white shark.png','Great white shark','Fish'),
('Guppy.png','Guppy','Fish'),
('Hammerhead shark.png','Hammerhead shark','Fish'),
('Horse mackerel.png','Horse mackerel','Fish'),
('Killifish.png','Killifish','Fish'),
('King salmon.png','King salmon','Fish'),
('Koi.png','Koi','Fish'),
('Loach.png','Loach','Fish'),
('Mahi-mahi.png','Mahi-mahi','Fish'),
('Mitten crab.png','Mitten crab','Fish'),
('Moray eel.png','Moray eel','Fish'),
('Napoleonfish.png','Napoleonfish','Fish'),
('Neon tetra.png','Neon tetra','Fish'),
('Nibble fish.png','Nibble fish','Fish'),
('Oarfish.png','Oarfish','Fish'),
('Ocean sunfish.png','Ocean sunfish','Fish'),
('Olive flounder.png','Olive flounder','Fish'),
('Pale chub.png','Pale chub','Fish'),
('Pike.png','Pike','Fish'),
('Piranha.png','Piranha','Fish'),
('Pond smelt.png','Pond smelt','Fish'),
('Pop-eyed goldfish.png','Pop-eyed goldfish','Fish'),
('Puffer fish.png','Puffer fish','Fish'),
('Rainbowfish.png','Rainbowfish','Fish'),
('Ranchu goldfish.png','Ranchu goldfish','Fish'),
('Ray.png','Ray','Fish'),
('Red snapper.png','Red snapper','Fish'),
('Ribbon eel.png','Ribbon eel','Fish'),
('Saddled bichir.png','Saddled bichir','Fish'),
('Salmon.png','Salmon','Fish'),
('Saw shark.png','Saw shark','Fish'),
('Sea bass.png','Sea bass','Fish'),
('Sea butterfly.png','Sea butterfly','Fish'),
('Sea horse.png','Sea horse','Fish'),
('Snapping Turtle.png','Snapping Turtle','Fish'),
('Soft-shelled turtle.png','Soft-shelled turtle','Fish'),
('Squid.png','Squid','Fish'),
('Stringfish.png','Stringfish','Fish'),
('Sturgeon.png','Sturgeon','Fish'),
('Suckerfish.png','Suckerfish','Fish'),
('Surgeonfish.png','Surgeonfish','Fish'),
('Sweetfish.png','Sweetfish','Fish'),
('Tadpole.png','Tadpole','Fish'),
('Tilapia.png','Tilapia','Fish'),
('Tuna.png','Tuna','Fish'),
('Whale shark.png','Whale shark','Fish'),
('Yellow perch.png','Yellow perch','Fish'),
('Zebra turkeyfish.png','Zebra turkeyfish','Fish'),
('Acanthostega.png','Acanthostega','Fossils'),
('Amber.png','Amber','Fossils'),
('Ammonite.png','Ammonite','Fossils'),
('Ankylo skull.png','Ankylo skull','Fossils'),
('Ankylo tail.png','Ankylo tail','Fossils'),
('Ankylo torso.png','Ankylo torso','Fossils'),
('Anomalocaris.png','Anomalocaris','Fossils'),
('Archaeopteryx.png','Archaeopteryx','Fossils'),
('Archelon skull.png','Archelon skull','Fossils'),
('Archelon tail.png','Archelon tail','Fossils'),
('Australopith.png','Australopith','Fossils'),
('Brachio chest.png','Brachio chest','Fossils'),
('Brachio pelvis.png','Brachio pelvis','Fossils'),
('Brachio skull.png','Brachio skull','Fossils'),
('Brachio tail.png','Brachio tail','Fossils'),
('Coprolite.png','Coprolite','Fossils'),
('Deinony tail.png','Deinony tail','Fossils'),
('Deinony torso.png','Deinony torso','Fossils'),
('Dimetrodon skull.png','Dimetrodon skull','Fossils'),
('Dimetrodon torso.png','Dimetrodon torso','Fossils'),
('Dinosaur track.png','Dinosaur track','Fossils'),
('Diplo chest.png','Diplo chest','Fossils'),
('Diplo neck.png','Diplo neck','Fossils'),
('Diplo pelvis.png','Diplo pelvis','Fossils'),
('Diplo skull.png','Diplo skull','Fossils'),
('Diplo tail tip.png','Diplo tail tip','Fossils'),
('Diplo tail.png','Diplo tail','Fossils'),
('Dunkleosteus.png','Dunkleosteus','Fossils'),
('Eusthenopteron.png','Eusthenopteron','Fossils'),
('Iguanodon skull.png','Iguanodon skull','Fossils'),
('Iguanodon tail.png','Iguanodon tail','Fossils'),
('Iguanodon torso.png','Iguanodon torso','Fossils'),
('Juramaia.png','Juramaia','Fossils'),
('Left megalo side.png','Left megalo side','Fossils'),
('Left ptera wing.png','Left ptera wing','Fossils'),
('Left quetzal wing.png','Left quetzal wing','Fossils'),
('Mammoth skull.png','Mammoth skull','Fossils'),
('Mammoth torso.png','Mammoth torso','Fossils'),
('Megacero skull.png','Megacero skull','Fossils'),
('Megacero tail.png','Megacero tail','Fossils'),
('Megacero torso.png','Megacero torso','Fossils'),
('Myllokunmingia.png','Myllokunmingia','Fossils'),
('Ophthalmo skull.png','Ophthalmo skull','Fossils'),
('Ophthalmo torso.png','Ophthalmo torso','Fossils'),
('Pachysaurus skull.png','Pachysaurus skull','Fossils'),
('Pachysaurus tail.png','Pachysaurus tail','Fossils'),
('Parasaur skull.png','Parasaur skull','Fossils'),
('Parasaur tail.png','Parasaur tail','Fossils'),
('Parasaur torso.png','Parasaur torso','Fossils'),
('Plesio body.png','Plesio body','Fossils'),
('Plesio skull.png','Plesio skull','Fossils'),
('Plesio tail.png','Plesio tail','Fossils'),
('Ptera body.png','Ptera body','Fossils'),
('Quetzal torso.png','Quetzal torso','Fossils'),
('Right megalo side.png','Right megalo side','Fossils'),
('Right ptera wing.png','Right ptera wing','Fossils'),
('Right quetzal wing.png','Right quetzal wing','Fossils'),
('Sabertooth skull.png','Sabertooth skull','Fossils'),
('Sabertooth tail.png','Sabertooth tail','Fossils'),
('Shark-tooth pattern.png','Shark-tooth pattern','Fossils'),
('Spino skull.png','Spino skull','Fossils'),
('Spino tail.png','Spino tail','Fossils'),
('Spino torso.png','Spino torso','Fossils'),
('Stego skull.png','Stego skull','Fossils'),
('Stego tail.png','Stego tail','Fossils'),
('Stego torso.png','Stego torso','Fossils'),
('T. rex skull.png','T. rex skull','Fossils'),
('T. rex tail.png','T. rex tail','Fossils'),
('T. rex torso.png','T. rex torso','Fossils'),
('Tricera skull.png','Tricera skull','Fossils'),
('Tricera tail.png','Tricera tail','Fossils'),
('Tricera torso.png','Tricera torso','Fossils'),
('Trilobite.png','Trilobite','Fossils');